# Assignment 2
For this assignment you'll be looking at 2017 data on immunizations from the CDC. Your datafile for this assignment is in [assets/NISPUF17.csv](assets/NISPUF17.csv). A data users guide for this, which you'll need to map the variables in the data to the questions being asked, is available at [assets/NIS-PUF17-DUG.pdf](assets/NIS-PUF17-DUG.pdf). **Note: you may have to go to your Jupyter tree (click on the Coursera image) and navigate to the assignment 2 assets folder to see this PDF file).**

In [2]:
mylist = ['ver','azul','verde']

for i,cor in enumerate(mylist):
    print(i)
    print(cor)

0
ver
1
azul
2
verde


## Question 1
Write a function called `proportion_of_education` which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

*This function should return a dictionary in the form of (use the correct numbers, do not round numbers):* 
```
    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}
```


In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('assets/NISPUF17.csv', index_col=0)
    
# Counts unique items in a column
counts = df['EDUC1'].value_counts()
counts

4    13656
3     6999
2     4906
1     2904
Name: EDUC1, dtype: int64

In [2]:
# Initial dictionary
final = {"college":None,
        "more than high school but not college":None,
        "high school":None,
        "less than high school":None}
    
# Then iterate through the indexes and items to calculate the percentage
for i,c in enumerate(counts):
    c = c/counts.sum()
        
    # Typecasting .keys() to list for a easier access by indexing
    final[list(final.keys())[i]] = c
final

{'college': 0.47974705779026877,
 'more than high school but not college': 0.24588090637625154,
 'high school': 0.172352011241876,
 'less than high school': 0.10202002459160373}

In [3]:
def proportion_of_education():
    import numpy as np
    import pandas as pd
    df = pd.read_csv('assets/NISPUF17.csv', index_col=0)
    
    # Counts unique items in a column
    counts = df['EDUC1'].value_counts()
    
    # Initial dictionary
    final = {"college":None,
            "more than high school but not college":None,
            "high school":None,
            "less than high school":None}
    
    # Then iterate through the indexes and items to calculate the percentage
    for i,c in enumerate(counts):
        c = c/counts.sum()
        
        # Typecasting .keys() to list for a easier access by indexing
        final[list(final.keys())[i]] = c
        
    return final
    
    #raise NotImplementedError()

In [4]:
assert type(proportion_of_education())==type({}), "You must return a dictionary."
assert len(proportion_of_education()) == 4, "You have not returned a dictionary with four items in it."
assert "less than high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "more than high school but not college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."


## Question 2

Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

*This function should return a tuple in the form (use the correct numbers:*
```
(2.5, 0.1)
```

In [6]:
    import numpy as np
    import pandas as pd
    df = pd.read_csv('assets/NISPUF17.csv', index_col=0)
    # fed breast milk (CBF_01)  (P_NUMFLU) – total number of seasonal influenza doses
    df[['CBF_01', 'P_NUMFLU']].head(10)

CBF_01  P_NUMFLU
1        1       NaN
2        2       NaN
3        2       NaN
4        2       3.0
5        1       0.0
6        2       NaN
7        1       0.0
8        1       0.0
9        1       0.0
10       1       NaN

In [7]:
df['CBF_01'].unique()

array([ 1,  2, 99, 77])

In [8]:
new_df = df[df['CBF_01'] < 3]
new_df['CBF_01'].unique()
# 1 is YES and 2 is No

array([1, 2])

In [9]:
new_df[['CBF_01', 'P_NUMFLU']].dropna().head()
#new_df[['CBF_01', 'P_NUMFLU']].fillna(0,axis=1)

CBF_01  P_NUMFLU
4       2       3.0
5       1       0.0
7       1       0.0
8       1       0.0
9       1       0.0

In [10]:
new_df[new_df['CBF_01'] == 1]['P_NUMFLU'].sum()

24986.0

In [11]:
new_df[new_df['CBF_01'] == 2]['P_NUMFLU'].sum()

3188.0

In [ ]:
df_splits[0][df_splits[0]['Provider_id'] == 'Provider_1']

In [12]:
new_df[['CBF_01', 'P_NUMFLU']].dropna().groupby('CBF_01').count()

P_NUMFLU
CBF_01          
1          13291
2           1997

In [13]:
# Sum of Influenza doses on Breast Fed babys
sum_y = new_df[new_df['CBF_01'] == 1]['P_NUMFLU'].sum()
    
# Sum of Influenza doses on not Breast Fed babys
sum_n = new_df[new_df['CBF_01'] == 2]['P_NUMFLU'].sum()
    
# Number of babys for each case
num_y = new_df[['CBF_01', 'P_NUMFLU']].groupby('CBF_01').count().loc[1]
num_n = new_df[['CBF_01', 'P_NUMFLU']].groupby('CBF_01').count().loc[2]

tup = float(sum_y/num_y) , float(sum_n/num_n)
print(tup)

(1.8799187420058687, 1.5963945918878317)


In [14]:
def average_influenza_doses():
    import numpy as np
    import pandas as pd
    df = pd.read_csv('assets/NISPUF17.csv', index_col=0)
    new_df = df[df['CBF_01'] < 3]
    
    # Sum of Influenza doses on Breast Fed babys
    sum_y = new_df[new_df['CBF_01'] == 1]['P_NUMFLU'].sum()
    
    # Sum of Influenza doses on not Breast Fed babys
    sum_n = new_df[new_df['CBF_01'] == 2]['P_NUMFLU'].sum()
    
    # Number of babys for each case
    num_y = new_df[['CBF_01', 'P_NUMFLU']].groupby('CBF_01').count().loc[1]
    num_n = new_df[['CBF_01', 'P_NUMFLU']].groupby('CBF_01').count().loc[2]
    
    return float(sum_y/num_y) , float(sum_n/num_n)
    #raise NotImplementedError()

In [15]:
assert len(average_influenza_doses())==2, "Return two values in a tuple, the first for yes and the second for no."


## Question 3
It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex. 

*This function should return a dictionary in the form of (use the correct numbers):* 
```
    {"male":0.2,
    "female":0.4}
```

Note: To aid in verification, the `chickenpox_by_sex()['female']` value the autograder is looking for starts with the digits `0.0077`.

In [16]:
# HAD_CPOX – 1(Yes) 2(No)
# SEX - 1(Male) 2(Female)
# P_NUMVRC – total number of varicella doses
import numpy as np
import pandas as pd
df = pd.read_csv('assets/NISPUF17.csv', index_col=0)
df[['SEX', 'HAD_CPOX', 'P_NUMVRC']].head(10).fillna(0)

SEX  HAD_CPOX  P_NUMVRC
1     1         2       0.0
2     1         2       0.0
3     2         2       0.0
4     2         2       1.0
5     2         2       0.0
6     1         2       0.0
7     2         2       1.0
8     2         2       0.0
9     1         1       0.0
10    1         2       0.0

In [17]:
df['HAD_CPOX'].unique()

array([ 2,  1, 77, 99])

In [18]:
vacc_df = df[(df['HAD_CPOX'] < 3) & (df['P_NUMVRC'] > 0)]
df2 = vacc_df[['SEX', 'HAD_CPOX', 'P_NUMVRC']]
df2.groupby(['SEX', 'HAD_CPOX']).count()

P_NUMVRC
SEX HAD_CPOX          
1   1               68
    2             7028
2   1               53
    2             6802

In [19]:
dff = df2.groupby(['SEX', 'HAD_CPOX']).count()
{"male":float(dff.loc[1,1]/dff.loc[1,2]), "female":float(dff.loc[2,1]/dff.loc[2,2])}

{'male': 0.009675583380762664, 'female': 0.0077918259335489565}

In [20]:
def chickenpox_by_sex():
    import numpy as np
    import pandas as pd
    df = pd.read_csv('assets/NISPUF17.csv', index_col=0)
    df[['SEX', 'HAD_CPOX', 'P_NUMVRC']].head(10).fillna(0)
    
    vacc_df = df[(df['HAD_CPOX'] < 3) & (df['P_NUMVRC'] > 0)]
    df2 = vacc_df[['SEX', 'HAD_CPOX', 'P_NUMVRC']]
    dff = df2.groupby(['SEX', 'HAD_CPOX']).count()
    
    return {"male":float(dff.loc[1,1]/dff.loc[1,2]), "female":float(dff.loc[2,1]/dff.loc[2,2])}
    #raise NotImplementedError()

In [21]:
assert len(chickenpox_by_sex())==2, "Return a dictionary with two items, the first for males and the second for females."


## Question 4
A correlation is a statistical relationship between two variables. If we wanted to know if vaccines work, we might look at the correlation between the use of the vaccine and whether it results in prevention of the infection or disease [1]. In this question, you are to see if there is a correlation between having had the chicken pox and the number of chickenpox vaccine doses given (varicella).

Some notes on interpreting the answer. The `had_chickenpox_column` is either `1` (for yes) or `2` (for no), and the `num_chickenpox_vaccine_column` is the number of doses a child has been given of the varicella vaccine. A positive correlation (e.g., `corr > 0`) means that an increase in `had_chickenpox_column` (which means more no’s) would also increase the values of `num_chickenpox_vaccine_column` (which means more doses of vaccine). If there is a negative correlation (e.g., `corr < 0`), it indicates that having had chickenpox is related to an increase in the number of vaccine doses.

Also, `pval` is the probability that we observe a correlation between `had_chickenpox_column` and `num_chickenpox_vaccine_column` which is greater than or equal to a particular value occurred by chance. A small `pval` means that the observed correlation is highly unlikely to occur by chance. In this case, `pval` should be very small (will end in `e-18` indicating a very small number).

[1] This isn’t really the full picture, since we are not looking at when the dose was given. It’s possible that children had chickenpox and then their parents went to get them the vaccine. Does this dataset have the data we would need to investigate the timing of the dose?

In [38]:
import scipy.stats as stats
import numpy as np
import pandas as pd
    
# this is just an example dataframe
df = pd.read_csv('assets/NISPUF17.csv', index_col=0)
df = df[['HAD_CPOX', 'P_NUMVRC']].dropna()

In [41]:
df = df[df['HAD_CPOX'] < 3]
df.head(10)

HAD_CPOX  P_NUMVRC
4          2       1.0
5          2       0.0
7          2       1.0
8          2       0.0
9          1       0.0
11         2       1.0
13         2       1.0
17         2       2.0
20         2       1.0
21         2       1.0

In [42]:
# here is some stub code to actually run the correlation
corr, pval=stats.pearsonr(df["HAD_CPOX"],df["P_NUMVRC"])
    
# just return the correlation
corr, pval

(0.07044873460147986, 2.7780263182916748e-18)

In [43]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    # this is just an example dataframe
    df = pd.read_csv('assets/NISPUF17.csv', index_col=0)
    
    df = df[['HAD_CPOX', 'P_NUMVRC']].dropna()
    # Filtering the missing data (77 = Dont Know and 99 = Missing)
    df = df[df["HAD_CPOX"] < 3]
    
    # here is some stub code to actually run the correlation
    corr, pval=stats.pearsonr(df["HAD_CPOX"],df["P_NUMVRC"])
    
    # just return the correlation
    return corr

    #raise NotImplementedError()

In [44]:
assert -1<=corr_chickenpox()<=1, "You must return a float number between -1.0 and 1.0."
